// Stack config: the live phase2→phase6 dev-dashboard-internal-api stack (#217→#221).
// Consumed by build-proto.js. Diffs live in protos/data/<pr>.diff.
module.exports = {
  out: "stack-viewer.html",
  planFile: "dev-dashboard-internal-api.plan.md",
  epic: {
    badge: "TDD",
    src: "docs/tdds/dev-dashboard-internal-api.md",
    title: "Dev Dashboard: Internal API Entity Operations",
    note: "No Jira ticket — this stack is TDD-driven; the plan calls the TDD the ticket stand-in.",
    goal: "Today every routine data fix in dev / prod-int runs through an engineer reading DynamoDB directly, and the only mutation the dashboard offers is <b>wiping the entire table</b>. This stack gives operators full create / read / update / delete over <code>Practice</code> and <code>Referral</code> records — plus a read-only preview of which practices the monthly batch would select and why — with every operation declared in the internal OpenAPI spec, typed, and covered by breaking-change detection.",
  },
  layers: [
    { pr: 217, phase: "phase 2", title: "repository layer — createPractice/Referral, patch*, ConflictError", adds: 693, dels: 129, files: 8, prov: "through-review", decisions: 3, edge: null,
      capability: "Manage practice + referral records — data layer",
      acids: ["PC-1", "PU-1", "PU-5", "PU-6", "PU-8", "RC-1", "RU-1", "RU-5", "RU-6", "PI-1", "RP-4"],
      summary: "The data-layer foundation the internal CRUD routes (phases 3–4) sit on. Adds <code>create</code>/<code>patch</code> and a <code>ConflictError</code> with fail-safe semantics — a patch can never upsert — but wires up <b>no routes or specs</b>. It exists so the API layers above have a correct, tested data contract to call." },
    { pr: 218, phase: "phase 3", title: "internal practice CRUD endpoints", adds: 2861, dels: 11, files: 22, prov: "through-review", decisions: 2, edge: "sits on <b>#217</b> — the service delegates to <code>createPractice</code>/<code>patchPractice</code>",
      capability: "Manage practice records — API",
      acids: ["PR-1", "PR-4", "PR-6", "PU-9", "PD-4", "PI-1"],
      summary: "Exposes the phase-2 repository to the dashboard as a typed HTTP contract: five practice CRUD endpoints plus the 404/409/422 response machinery the internal spec lacked. Exists to turn the data methods into a reviewable API surface — the correctness of which rests entirely on #217." },
    { pr: 219, phase: "phase 4", title: "internal PCP referral CRUD endpoints", adds: 1406, dels: 2, files: 8, prov: "through-review", decisions: 1, edge: "mirrors <b>#218</b> for referrals; reuses #217 repository methods",
      capability: "Manage referral records — API",
      acids: ["RR-4", "RR-6", "RU-1", "RD-4", "RP-1", "RP-2", "RP-3", "RP-4"],
      summary: "The same CRUD shape as phase 3, but for the PHI-carrying referral entity. Exists so referrals get an internal surface identical to practices; it mirrors the practice routes rather than sharing a generic because the two diverge on patch semantics and index shape." },
    { pr: 220, phase: "phase 5", title: "extract @attribution-service/practice-cohort + cohort preview", adds: 736, dels: 75, files: 37, prov: "through-review", decisions: 1, edge: null,
      capability: "Preview the monthly batch cohort — shared package + endpoint",
      acids: ["CX-1", "CX-2", "CX-3", "CX-4", "CX-5", "CX-6", "CP-5", "CP-6", "CP-8"],
      summary: "Extracts the M2 batch's cohort selection and guards into a shared package so the dashboard preview <b>cannot drift</b> from batch behavior, then adds a read-only preview endpoint on top. Exists to guarantee the preview resolves the cohort exactly as the monthly batch would — with no code path that emits a batch metric." },
    { pr: 221, phase: "phase 6", title: "dev-dashboard CRUD + cohort preview pages", adds: 2274, dels: 33, files: 20, prov: "through-review", decisions: 1, edge: "consumes the <b>#218/#219</b> API and <b>#220</b> cohort package",
      capability: "All three capabilities — dashboard UI",
      acids: ["RP-1", "RP-2", "RP-3", "CP-6"],
      summary: "The consumer that makes the internal API usable by humans: one page per entity plus the read-only cohort preview, on test infrastructure the dashboard never had. Plan-flagged as <b>separable</b> — every API-layer AC still holds without it." },
  ],
  decisions: {
    A: { layer: "0", num: "D1", prov: "through-review", title: "Add ConflictError mirroring the NotFoundError shape",
      chose: "A dedicated <code>ConflictError</code> in <code>errors.ts</code>, same constructor/name shape as the existing <code>NotFoundError</code>.",
      ck: "Instead of", cv: "a generic <span class='strike'>Error</span> or reusing NotFoundError",
      why: "Create-collision is a distinct outcome from not-found; the repository maps a rejected create to it so callers can branch on the class rather than parse a message. (AC X-9)", edge: null },
    B: { layer: "0", num: "D2", prov: "through-review", title: "Detect create collisions with returnOnConditionCheckFailure, not string matching",
      chose: "<code>create().go({ returnOnConditionCheckFailure: true })</code> and branch on <code>result.rejected</code> → throw <code>ConflictError</code>.",
      ck: "Instead of", cv: "<span class='strike'>error.message.includes(\"ConditionalCheckFailed\")</span>, which deletePractice/deleteReferral still rely on",
      why: "The flag turns a thrown ElectroError into a structured <code>{ rejected }</code>, so collision detection stops depending on a message substring. The two delete* methods are deliberately left on the old path — out of scope, follow-up ticket.",
      edge: { to: "#218", text: "<code>internal-practice-service.createPractice</code> calls this and lets <code>ConflictError</code> surface as a 409." } },
    C: { layer: "0", num: "D3", prov: "through-review", title: "A patch can never upsert — resolve null when the record is absent",
      chose: "<code>patchPractice</code> maps a rejected patch to <code>null</code> (not-found) rather than creating the row.",
      ck: "Instead of", cv: "<span class='strike'>patch() semantics that create-on-missing</span>",
      why: "An internal PATCH must 404 on a missing id, not silently create it. Same structural detection as create (<code>result.rejected</code>). Contrast with <code>upsertReferral</code>, whose omission-means-wipe semantics serve the Hex ingest.",
      edge: { to: "#218", text: "<code>updatePractice</code> returns 404 when this resolves <code>null</code>." } },
    D: { layer: "1", num: "D1", prov: "through-review", title: "Response mirrors what is stored — omit absent optionals, never serialize null",
      chose: "<code>toInternalPractice</code> spreads optional fields only when <code>!== undefined</code>.",
      ck: "Instead of", cv: "<span class='strike'>emitting null for every absent optional</span>",
      why: "A response should reflect the actual stored item; a client can't tell \"unset\" from \"explicitly null\" if absent fields serialize as null.", edge: null },
    E: { layer: "1", num: "D2", prov: "through-review", title: "Thin service layer delegates to the repository, adds only the wire mapping",
      chose: "<code>createPractice</code>/<code>updatePractice</code> call the repository and wrap the result in <code>toInternalPractice</code>; no business logic in the route.",
      ck: "Instead of", cv: "<span class='strike'>reaching into ElectroDB from the route handler</span>",
      why: "Keeps the HTTP boundary a pure mapping layer so the collision/absent semantics live in exactly one place — #217's repository. This is the seam: the entire API surface's correctness rests on the lower layer.",
      edge: { to: "#217", text: "Delegates to <code>practiceRepository.createPractice</code> (D2) and <code>patchPractice</code> (D3). Review #217 first — this layer inherits its guarantees." } },
    F: { layer: "2", num: "D1", prov: "through-review", title: "Referral CRUD mirrors the practice routes rather than abstracting a generic",
      chose: "Duplicate the practice route/service shape for referrals with referral-specific types.",
      ck: "Instead of", cv: "<span class='strike'>a generic entity-CRUD abstraction over both</span>",
      why: "The two entities diverge on patch semantics (upsert vs patch) and index shape; a shared generic would leak those differences back out as options.", edge: null },
    G: { layer: "3", num: "D1", prov: "through-review", title: "Extract practice-cohort into its own package, exposing resolveCohort",
      chose: "New <code>@attribution-service/practice-cohort</code> workspace package exporting <code>resolveCohort</code> (SOLD selection; caller owns metric emission), consumed by the M2 batch and the dashboard preview.",
      ck: "Instead of", cv: "<span class='strike'>inlining cohort selection in the batch runner</span>",
      why: "The dashboard preview must resolve the cohort <em>exactly</em> as the monthly batch would; a shared package guarantees one implementation so the preview can't drift from what the batch actually does.", edge: null },
    H: { layer: "4", num: "D1", prov: "through-review", title: "Dashboard pages call the internal API, hold no data logic",
      chose: "CRUD + cohort-preview pages issue requests to the #218/#219 endpoints and render responses.",
      ck: "Instead of", cv: "<span class='strike'>a second data path from the UI</span>",
      why: "The internal API is the single source of the CRUD contract; the UI is a consumer so the collision/patch/absent semantics are never re-implemented client-side.",
      edge: { to: "#218/#219", text: "Every mutation the UI offers is one of the endpoints those layers added." } },
  },
  anchors: [
    { file: "packages/data/src/errors.ts", sub: "export class ConflictError", d: "A" },
    { file: "repository/practice-repository.ts", sub: "async createPractice(", d: "B" },
    { file: "repository/practice-repository.ts", sub: "returnOnConditionCheckFailure: true", d: "B" },
    { file: "repository/practice-repository.ts", sub: "throw new ConflictError", d: "B" },
    { file: "repository/practice-repository.ts", sub: "async patchPractice(", d: "C" },
    { file: "repository/practice-repository.ts", sub: "if (result.rejected) return null", d: "C" },
    { file: "service/internal-practice-service.ts", sub: "export function toInternalPractice", d: "D" },
    { file: "service/internal-practice-service.ts", sub: "await practiceRepository.createPractice", d: "E" },
    { file: "service/internal-practice-service.ts", sub: "await practiceRepository.patchPractice", d: "E" },
    { file: "practice-cohort/src/cohort.ts", sub: "export const resolveCohort", d: "G" },
    { file: "practice-cohort/src/index.ts", sub: "resolveCohort", d: "G" },
    { file: "dev-dashboard", sub: "if (status === 409)", d: "H" },
    { file: "dev-dashboard", sub: "async function request<T>", d: "H" },
  ],
};
